/**!
 dapentry runtime library
    Copyright 2021-2022 Stephan Smola,
    See https://dapentry.com for more information

 THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
 REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
 FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
 INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS
 OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
 TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
 THIS SOFTWARE.


 This software uses d3, https://d3js.org:
    Copyright 2010-2022 Mike Bostock
    License: https://github.com/d3/d3/blob/main/LICENSE

 @licence
 */



export * from "../library"
export {SvgObjectRenderer as SVGRenderer} from "../../ui/drawing/SvgObjectRenderer";


