/*
 * Generated by PEG.js 0.10.0.
 *
 * http://pegjs.org/
 */

"use strict";

var TokenTypes = require("./TokenTypes");


module.exports = {
  SyntaxError: peg$SyntaxError,
  parse:       peg$parse
};
